# Generated by Django 5.0 on 2023-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcard',
            name='card_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
