# Generated by Django 5.0 on 2023-12-12 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildcard', '0002_alter_contactcard_card_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='card_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'Only numeric characters are allowed.')]),
        ),
    ]
